# Generated by Django 5.2.11 on 2026-03-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(help_text='RUT del beneficiario, formato 12.345.678-9', max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rsh_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percentil RSH del hogar (0.00 – 100.00).', max_digits=5, null=True)),
                ('ahorro_uf', models.DecimalField(blank=True, decimal_places=2, help_text='Ahorro acreditado del beneficiario, en UF.', max_digits=10, null=True)),
                ('ahorro_minimo_uf', models.DecimalField(blank=True, decimal_places=2, help_text='Ahorro mínimo requerido según subsidio, en UF.', max_digits=10, null=True)),
                ('puntaje_match', models.IntegerField(blank=True, help_text='Puntaje de compatibilidad calculado por la IA.', null=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('alerta', 'Alerta'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'beneficiario',
                'verbose_name_plural': 'beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='ModuloIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80, unique=True)),
                ('nombre_mostrar', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Activo', max_length=30)),
                ('config_json', models.JSONField(blank=True, help_text='Configuración específica del módulo (prompts, umbrales, etc.).', null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'módulo IA',
                'verbose_name_plural': 'módulos IA',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(help_text='RUT de la organización, formato 12.345.678-K', max_length=12, unique=True)),
                ('tipo', models.CharField(choices=[('egis', 'EGIS'), ('constructora', 'Constructora'), ('laboratorio', 'Laboratorio / Universidad'), ('otro', 'Otro')], db_index=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(default='Biobío', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('vigencia_maxima', models.IntegerField(help_text='0 = debe estar vigente al momento de presentación.')),
                ('unidad', models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses'), ('vigente', 'Debe estar vigente')], default='dias', max_length=20)),
                ('obligatorio', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'regla de documento',
                'verbose_name_plural': 'reglas de documento',
            },
        ),
        migrations.CreateModel(
            name='ReglaSubsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: DS49, DS1, Título II DS49', max_length=40, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('ahorro_minimo_uf', models.DecimalField(decimal_places=2, default=0, help_text='Ahorro mínimo exigido al beneficiario, en UF.', max_digits=10)),
                ('rsh_maximo_pct', models.DecimalField(decimal_places=2, default=100, help_text='Percentil RSH máximo permitido (0-100).', max_digits=5)),
                ('puntaje_corte', models.IntegerField(default=0, help_text='Puntaje de corte para calificación SERVIU.')),
                ('tope_uf', models.DecimalField(decimal_places=2, default=0, help_text='Tope del subsidio en UF.', max_digits=10)),
                ('fuente', models.CharField(blank=True, help_text='Referencia normativa: decreto, artículo, etc.', max_length=100)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'regla de subsidio',
                'verbose_name_plural': 'reglas de subsidio',
            },
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('visado', 'Visado'), ('listo_serviu', 'Listo SERVIU'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('estado_subsidio', models.CharField(blank=True, max_length=80)),
                ('monto_uf', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total del subsidio asignado, en UF.', max_digits=10, null=True)),
                ('visto_bueno_ito', models.BooleanField(default=False)),
                ('check_seremi', models.BooleanField(default=False)),
                ('resolucion', models.BooleanField(default=False)),
                ('informe_universidad', models.BooleanField(default=False, help_text='Requerido para casos de silófagos (termitas).')),
                ('listo_para_facturar', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta', to='egis_app.beneficiario')),
            ],
            options={
                'verbose_name': 'carpeta',
                'verbose_name_plural': 'carpetas',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, help_text='Ruta en Supabase Storage o filesystem local.', max_length=500)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('alerta', 'Alerta'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('vigencia', models.CharField(blank=True, choices=[('vigente', 'Vigente'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido')], max_length=20, null=True)),
                ('extraccion_json', models.JSONField(blank=True, help_text='Datos extraídos por OCR/IA (RUT, fechas, montos, etc.).', null=True)),
                ('score_confianza', models.FloatField(blank=True, help_text='Confianza de la IA en la extracción (0.0 – 1.0).', null=True)),
                ('validacion_humana', models.BooleanField(blank=True, help_text='null = sin revisar; True = aprobado por operador; False = rechazado por operador.', null=True)),
                ('nota_rechazo', models.TextField(blank=True, help_text='Motivo de rechazo si estado = rechazado.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='egis_app.carpeta')),
                ('regla_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='egis_app.regladocumento')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=100)),
                ('dias_restantes', models.IntegerField()),
                ('severidad', models.CharField(choices=[('critical', 'Crítica'), ('warning', 'Advertencia')], max_length=20)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='egis_app.beneficiario')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='egis_app.documento')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='InformeTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_informe', models.CharField(choices=[('informe_plagas', 'Informe Plagas (silófagos)'), ('seremi_quimicos', 'SEREMI – Riesgo Químico'), ('laboratorio_suelos', 'Laboratorio de Suelos'), ('otro', 'Otro')], max_length=80)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500)),
                ('fecha_emision', models.DateField(blank=True, help_text='Fecha de emisión del informe.', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del informe (si aplica).', null=True)),
                ('resultado', models.TextField(blank=True, help_text='Resumen del resultado o conclusión técnica.')),
                ('seremi_aprobado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_terceros', to='egis_app.carpeta')),
                ('entidad_emisora', models.ForeignKey(blank=True, help_text='Universidad, SEREMI o laboratorio que emite el informe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_emitidos', to='egis_app.organizacion')),
            ],
            options={
                'verbose_name': 'informe de tercero',
                'verbose_name_plural': 'informes de terceros',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, help_text='Ej: Vivienda nueva, Mejoramiento, Ampliación', max_length=50)),
                ('clasificacion', models.CharField(blank=True, help_text='Ej: DS49 Título I, DS1 Tramo 1', max_length=80)),
                ('cantidad_beneficiarios', models.IntegerField(default=0)),
                ('avance_pct', models.IntegerField(default=0, help_text='Porcentaje de avance constructivo (0-100).')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_tramite', 'En trámite'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='activo', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('constructora', models.ForeignKey(blank=True, help_text='Constructora asignada al proyecto.', limit_choices_to={'tipo': 'constructora'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_como_constructora', to='egis_app.organizacion')),
                ('egis', models.ForeignKey(blank=True, help_text='EGIS responsable del proyecto.', limit_choices_to={'tipo': 'egis'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_como_egis', to='egis_app.organizacion')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='egis_app.proyecto'),
        ),
        migrations.CreateModel(
            name='RegistroContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos_faltantes', models.JSONField(default=list)),
                ('urgencia', models.CharField(choices=[('critical', 'Crítica'), ('warning', 'Advertencia'), ('info', 'Informativa')], max_length=20)),
                ('ultimo_contacto_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='egis_app.beneficiario')),
            ],
            options={
                'verbose_name': 'registro de contacto',
                'verbose_name_plural': 'registros de contacto',
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='subsidio_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiarios', to='egis_app.reglasubsidio'),
        ),
        migrations.CreateModel(
            name='LogVisado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('observado', 'Observado'), ('revertido', 'Revertido')], max_length=20)),
                ('origen', models.CharField(choices=[('ia', 'Inteligencia Artificial'), ('humano', 'Operador Humano'), ('sistema', 'Proceso Automático')], default='humano', max_length=20)),
                ('usuario', models.CharField(blank=True, help_text='Username o email del operador. Vacío si origen = IA.', max_length=150)),
                ('detalle', models.TextField(blank=True, help_text='Motivo, observación o nota de la acción.')),
                ('score_ia', models.FloatField(blank=True, help_text='Score de confianza de la IA al momento del visado.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales del contexto de visado.', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_visado', to='egis_app.documento')),
            ],
            options={
                'verbose_name': 'log de visado',
                'verbose_name_plural': 'logs de visado',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['documento', '-creado_en'], name='idx_log_visado_doc_fecha')],
            },
        ),
        migrations.AddIndex(
            model_name='beneficiario',
            index=models.Index(fields=['rut'], name='idx_beneficiario_rut'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiario',
            unique_together={('proyecto', 'rut')},
        ),
    ]
